Feature/112 model configs
NCAR/wrfcloud pull request #131
Opened 2023-02-07 02:29 UTC by hahnd

## Expected Differences ##

- [ ] Do these changes modify the system output in any way? **[Yes or No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
- [ ] Review the source issue metadata (labels, project, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Project**
Select: **Milestone** as the version that will include these changes
Select: **Development** to link to the original development issue.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2023-02-07 15:55 UTC, georgemccabe commented on python/src/wrfcloud/aws/resources/cf_imagebuilder_wrf_intel.yaml
> +                    - git clone -b feature/112-model-configs https://github.com/NCAR/wrfcloud
Should this be develop since this branch will go away when it is merged?
```suggestion
                    - git clone -b develop https://github.com/NCAR/wrfcloud
```

2023-02-07 16:00 UTC, georgemccabe commented on python/src/wrfcloud/config/config.py
> +        return f'configurations/{self.name}/geo_em.d01.nc'
Should this be a list since there can be multiple geo_em files for each domain?

2023-02-07 16:22 UTC, georgemccabe commented on python/src/wrfcloud/config/config.py
> +        return f'configurations/{self.name}/geo_em.d01.nc'
I'm realizing that each configuration may only have 1 domain. If that is the case, the logic in geogrid.py could be cleaned up since it supports multiple domains defined in the namelist.wps file

2023-02-07 16:23 UTC, georgemccabe commented on python/src/wrfcloud/jobs/job.py
> +        return os.environ['WPS_HOME'] if 'WPS_HOME' in os.environ else '/home/ec2-user/WPS'
This could be simplified:
```suggestion
        return os.environ.get('WPS_HOME', '/home/ec2-user/WPS')
```

2023-02-07 16:24 UTC, georgemccabe commented on python/src/wrfcloud/jobs/job.py
> +        base_dir: str = os.environ['WORK_DIR'] if 'WORK_DIR' in os.environ else '/data'
```suggestion
        base_dir: str = os.environ.get('WORK_DIR', '/data')
```

2023-02-07 16:28 UTC, georgemccabe commented on python/src/wrfcloud/runtime/geogrid.py
> +        if not os.path.exists(self.geogrid_dir):
Can we remove the exists check if we are using exists_ok=True in os.makedirs?

2023-02-07 16:54 UTC, georgemccabe requested changes
I made a few in-line comments, mostly code cleanup.

Question: Can more than 1 domain be specified per configuration? It looks like there is some inconsistency among the runtime tools where some support multiple and some don't.

I wasn't able to get the unit tests to run successfully, so there may be some minor changes to get that working again.

I looked over the typescript changes but I am rusty on my JavaScript syntax so I couldn't perform a sufficient review of those changes.

It may be good to have someone play around with the UI to see if it works as expected and see if anything breaks.

2023-02-07 16:56 UTC, georgemccabe commented
I fixed the unit tests. There were 2 incorrect imports of WrfConfig. I will push the changes to this branch.

2023-02-08 21:22 UTC, hahnd commented on python/src/wrfcloud/aws/resources/cf_imagebuilder_wrf_intel.yaml
> +                    - git clone -b feature/112-model-configs https://github.com/NCAR/wrfcloud
John is working on a fix for this in a separate branch.

2023-02-08 21:23 UTC, hahnd commented on python/src/wrfcloud/config/config.py
> +        return f'configurations/{self.name}/geo_em.d01.nc'
Leaving as is for now after discussing in yesterday's meeting.  Kate will open a new issue to support multiple domains.

2023-02-08 21:27 UTC, hahnd commented on python/src/wrfcloud/runtime/geogrid.py
> +        if not os.path.exists(self.geogrid_dir):
Yes, making this change.

2023-02-08 21:39 UTC, merged