Feature/126 install docs
NCAR/wrfcloud pull request #136
Opened 2023-02-11 16:29 UTC by JohnHalleyGotway

## Expected Differences ##

- [x] Do these changes modify the system output in any way? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
I spent a long time testing this behavior in the METplus AWS account. WRF Cloud is current installed/running at app.metpluscloud.org.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Primarily, review the updated `System Installation` chapter for this PR via Read-The-Docs at this link...

@hahnd: Please primarily review the non-documentation edits. 
@bruckerd: 
Please feel free to recommend edits, re-wording, additional details as needed.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[Yes]**
No automated testing, but manual testing at app.metpluscloud.org.

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[Wed 2/15/23]**.</br>

## Pull Request Checklist ##
- [x] Review the source issue metadata (labels, project, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Project**
Select: **Milestone** as the version that will include these changes
Select: **Development** to link to the original development issue.
- [x] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2023-02-13 17:13 UTC, fossell commented on docs/Users_Guide/installation.rst
> +
Should we add info about what these things are? E.g. what does enabling autocompletion mean? Where should this info exist, i.e. here within each question or elsewhere?

2023-02-13 17:14 UTC, fossell commented on docs/Users_Guide/installation.rst
> +  * Enter host name for web application: [e.g. app.{DOMAIN}]
Should we somehow indicate that {DOMAIN} is what was entered in the previous question or from prereqs?

2023-02-13 17:15 UTC, fossell commented on docs/Users_Guide/installation.rst
> +  * Paste your public key, often found at ${HOME}/.ssh/id_rsa.pub:
Add documentation link for creating one or is that overkill?

2023-02-13 17:20 UTC, fossell commented on docs/Users_Guide/installation.rst
> +    b. If it exists, run the following commands to update the WRF Cloud web files:
Is there a condition where this doesn't exist but the user still experiences the weird download file behavior?

2023-02-13 17:22 UTC, fossell reviewed
@JohnHalleyGotway - Added a few comments/questions for clarification.

2023-02-13 17:31 UTC, JohnHalleyGotway commented on docs/Users_Guide/installation.rst
> +    b. If it exists, run the following commands to update the WRF Cloud web files:
Yes, if they run the install steps, go home for the day, and check the next day (as I did), the temp files will have likely already been scrubbed.

Note that @hahnd is checking with AWS to see if this behavior can be avoided entirely. So ideally it'll be resolved another way and we can remove this rather clunky patching step. But until we actually solve that, I think it's good to include these steps.

2023-02-13 17:34 UTC, JohnHalleyGotway commented on docs/Users_Guide/installation.rst
> +  * Paste your public key, often found at ${HOME}/.ssh/id_rsa.pub:
Do you want me to include a link to https://git-scm.com/book/en/v2/Git-on-the-Server-Generating-Your-SSH-Public-Key?

2023-02-14 00:53 UTC, hahnd approved these changes

2023-02-14 00:53 UTC, hahnd commented on python/src/wrfcloud/aws/resources/cf_imagebuilder_wrf_intel.yaml
> +                    - git clone ${GIT_CLONE_OPTS} https://github.com/NCAR/wrfcloud
Made these changes with commit ID: 945d9305f244636172d27c1704fe92ff7697fdae

2023-02-14 15:01 UTC, fossell requested changes
@JohnHalleyGotway - I provided some content suggestions.

2023-02-14 15:01 UTC, fossell commented on docs/Users_Guide/installation.rst
> +  * Would you like to enable autocompletion? [*Recommend Yes*]
```suggestion
  * Would you like to enable autocompletion? [*Recommend Yes*]
     * This is required to install Angular, which creates the website. Please answer Yes.
```

2023-02-14 15:02 UTC, fossell commented on docs/Users_Guide/installation.rst
> +
Added suggestions.

2023-02-14 15:03 UTC, fossell commented on docs/Users_Guide/installation.rst
> +The prerequisites for installing WRF Cloud in an AWS account are described below.
@hahnd - Can you please review the wording and suggest changes to make sure this is technically correct?

2023-02-14 15:57 UTC, fossell commented on docs/Users_Guide/installation.rst
> +5. After completing these steps, check the email address provided above to verify it. It takes approximately 10-20 minutes for the website to become available.
The numbering is off, this is the second step 5.

2023-02-14 23:25 UTC, JohnHalleyGotway commented
After incorporating recommend changes from @fossell and updates to this feature branch from @hahnd, I am proceeding with one final round of testing by following the PR version of the [System Installation](https://wrfcloud--136.org.readthedocs.build/en/136/Users_Guide/installation.html) instructions:

1. Uninstall the metpluscloud.org.
   - Tweaked the wording slightly.
   - Did have to redo deleting `WrfCloudApiData` because it couldn't be deleted until `WrfCloudWebApp` was gone.
   - Confirmed that I can no longer log into app.metpluscloud.org as expected.
2. Re-install at metpluscloud.org.
   - I note that the "autocompletion" question has disappeared. The first question is about the domain name. I'll remove the note about autocompletion.
   - The install went smooth and I was able to log on WITHOUT any odd download behavior. Recommend keeping the "download" behavior troubleshooting instructions until someone else confirms that they're no longer needed.
   - Confirmed that the sample carribean domain does now exist. So @hahnd's fix worked.
   - Confirmed that I can add new users (Kate, David, and George).
   - Found in the CloudFormation `Parameters` tab that `GitCloneOpts` was correctly set as `--branch feature/126-install-docs`.
   - Takes a long time for the EC2 image to build... still waiting.

2023-02-15 17:50 UTC, JohnHalleyGotway commented
@fossell I did make some edits to the install docs since you last reviewed ([7d4284a](https://github.com/NCAR/wrfcloud/pull/136/commits/7d4284a77bafa00fd9d0170fe2a7492ca593d3d1), [6534979](https://github.com/NCAR/wrfcloud/pull/136/commits/6534979e0217f0ec81686909b92dde7beb8ca09d), [0c6138d](https://github.com/NCAR/wrfcloud/pull/136/commits/0c6138d90b725493502b470f4fb7ffaf19b17e4f)). But I think we're in good shape now.

2023-02-15 20:21 UTC, fossell approved these changes
Updates to install guide look good. I'm also able to activate an account for this install test, indicating the install was successful from that standpoint.

2023-02-15 20:27 UTC, merged