Feature #26 error handling for processes
NCAR/wrfcloud pull request #197
Opened 2023-05-08 18:37 UTC by georgemccabe

Closes #26

We should create a related issue to enhance UI to allow users to easily view the log files.

## Expected Differences ##

- [X] Do these changes modify the system output in any way? **[Yes]**</br>

Failures from each process are caught and reported to UI.
Status message displayed on UI for a failed job will include the process name, e.g. `GeoGrid failed`, if the process returned a non-zero error code, if none of the expected output files exist, or if the log file does not contain text that signifies a successful run. If something else goes wrong in the run logic, the status message will just say `Failed`.

## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>

* Modified expected file paths, log file path, and string to find in log file to force runs to fail -- confirmed the expected error message is shown as the job status message
* Set small domain configuration (midwest_test_cores) to use 96 cores, which previously caused a failure, and confirmed that the failure is now caught from the application that failed (Ungrib).

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

* Review code changes
* (Optionally) create a bad configuration (namelist) that should cause a failure and confirm that the expected process is listed in the status message for the failure.

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No]**

We should provide more information on expected status messages on failure (see above).

- [X] Do these changes include sufficient testing updates? **[Yes]**

- [X] Will this PR result in changes to the test suite? **[No]**</br>

- [X] Please complete this pull request review by **5/11/2023**.</br>

## Pull Request Checklist ##
- [X] Review the source issue metadata (labels, project, and milestone).
- [X] Complete the PR definition above.
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [X] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Project**
Select: **Milestone** as the version that will include these changes
Select: **Development** to link to the original development issue.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2023-05-09 16:15 UTC, fossell commented
@georgemccabe - Can you make two new Issues to capture the enhancements noted in this PR, e.g. 1) _Reduce duplicate code in the run\_* functions for each Process sub-class that could be pulled up to the Process class._ and 2) _refactor the logic to write files to explicit directories to avoid switching directories._  These can be placed in the backlog milestone so we don't lose track of these improvements. I added an addition issue #200 for documentation related to this PR and job status, but as noted in that issue I'm holding off in case work on #198 changes documentation as well.

2023-05-09 16:15 UTC, fossell commented
@georgemccabe - Also thanks for finding and fixing that readthedocs issue! I was having the same problem but hadn't figured out how to fix it.

2023-05-09 16:18 UTC, fossell approved these changes
Errors are being caught as expected. We tested two changes together per my suggestions and both failed and displayed on the UI as expected. My review approval is based on functionality standpoint.

2023-05-11 18:40 UTC, hahnd requested changes

2023-05-11 18:40 UTC, hahnd commented on python/src/wrfcloud/runtime/run.py
> +    except WRFCloudError as e:
I would suggest removing the case to catch the WRFCloudError and handling it differently.  The messages passed to log.fatal() may not always be user-friendly.  The user will be able to see the log message in the log files if they choose to view the log files and debug.

2023-05-11 18:49 UTC, hahnd commented on python/src/wrfcloud/runtime/__init__.py
> +            for expected_path in self.expected_output:
pylint gives an error on this line because _self.expected_output_ may be None and is not non-iterable.

2023-05-11 18:52 UTC, hahnd commented on python/src/wrfcloud/runtime/__init__.py
> +        self.expected_output: Union[None, list] = None
expected_output may be a list of what?  Strings?  Maybe use `Union[None, List[str]]`

2023-05-15 16:36 UTC, georgemccabe commented on python/src/wrfcloud/runtime/__init__.py
> +            for expected_path in self.expected_output:
There is a check if self.expected_output is None and the loop is not reached if it is None. Is there another way to handle this?

2023-05-16 16:56 UTC, hahnd approved these changes

2023-05-16 17:25 UTC, merged