Feature #188 restrict dates in forecast selector
NCAR/wrfcloud pull request #213
Opened 2023-06-12 20:39 UTC by georgemccabe

Closes #188 

Restrict the dates that can be selected for Cycle Date in the Launch WRF page to no later than today's date and not before Feb. 26, 2021 because the input data is not available in S3 before that date.

NOTE: WebStorm reports an error when the min/max values are added to the HTML. Apparently this is a bug as the syntax works as expected (see [this comment](https://github.com/angular/components/issues/24572#issuecomment-1083633904)).

## Expected Differences ##

- [X] Do these changes modify the system output in any way? **[No]**</br>

## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>

Started angular locally and confirmed that the date selector is properly restricted.

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Test locally if desired

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [X] Do these changes include sufficient testing updates? **[Yes]**

- [X] Will this PR result in changes to the test suite? **[No]**</br>

- [X] Please complete this pull request review by **6/13/2023**.</br>

## Pull Request Checklist ##
- [X] Review the source issue metadata (labels, project, and milestone).
- [X] Complete the PR definition above.
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [X] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Project**
Select: **Milestone** as the version that will include these changes
Select: **Development** to link to the original development issue.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2023-06-13 18:37 UTC, hahnd commented on web/src/app/launch-wrf/launch-wrf.component.ts
> +    // earliest date to select is Feb. 26, 2021
https://github.com/NCAR/wrfcloud/assets/7718310/e462eb10-4ee4-415f-a6d7-3725ba0ab71f

2023-06-16 19:55 UTC, georgemccabe commented
@hahnd, I made the updates you suggested. A good test would be to start angular, open the date selector, and see if the next date becomes select-able at 6pm MST. I tested using time offsets and it appeared to be properly using the UTC time to determine the last date.

2023-06-16 20:03 UTC, georgemccabe commented
@hahnd , also note I had to set this.minDate and this.maxDate in the constructor because it complained that those variables aren't necessarily set in the constructor even though the constructor called the function that sets them.

2023-06-20 14:49 UTC, hahnd requested changes

2023-06-20 14:49 UTC, hahnd commented on web/src/app/launch-wrf/launch-wrf.component.ts
> +    setTimeout(this.refreshDateRange.bind(this), next_day.diff(this.maxDate, 'seconds'));
The `setTimeout` function takes a value in _milliseconds_.  The `'seconds'` parameter should be left out in the call to the `diff` function so that the units match.  The default units from `diff` is milliseconds.

2023-06-20 16:49 UTC, georgemccabe commented on web/src/app/launch-wrf/launch-wrf.component.ts
> +    setTimeout(this.refreshDateRange.bind(this), next_day.diff(this.maxDate, 'seconds'));
```suggestion
    setTimeout(this.refreshDateRange.bind(this), next_day.diff(this.maxDate));
```

2023-06-20 18:14 UTC, merged