Feature #183, added screenshots to install and uninstall instructions
NCAR/wrfcloud pull request #225
Opened 2023-07-05 19:03 UTC by georgemccabe

Closes #183

## Expected Differences ##

- [X] Do these changes modify the system output in any way? **[No]**</br>

## Pull Request Testing ##

- [X] Describe testing already performed for these changes:</br>

Reviewed documentation updates

- [X] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Review documentation updates and screenshots. Rendered content can be found here:
https://wrfcloud.readthedocs.io/en/feature_183_screenshots/Users_Guide/installation.html

- [X] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [X] Do these changes include sufficient testing updates? **[Yes]**

- [X] Will this PR result in changes to the test suite? **[No]**</br>

- [X] Please complete this pull request review by **7/10/2023**.</br>

## Pull Request Checklist ##
- [X] Review the source issue metadata (labels, project, and milestone).
- [X] Complete the PR definition above.
- [X] Ensure the PR title matches the feature or bugfix branch name.
- [X] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Project**
Select: **Milestone** as the version that will include these changes
Select: **Development** to link to the original development issue.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2023-07-05 19:48 UTC, hahnd requested changes

2023-07-05 19:48 UTC, hahnd commented on docs/_static/uninstall_5b_delete_email.png
Let's blur-out the email address here.

2023-07-05 19:48 UTC, hahnd commented on docs/_static/install_12_ami_complete.png
I think AWS typically blurs out account id and usernames in their screen captures.  Probably not detrimental alone, however it does reveal partial login information, which should be kept secret.  Now that this is in the public domain, make sure you have a strong and unique password.

2023-07-05 19:48 UTC, hahnd commented on docs/_static/install_13a_image_builder.png
blur username/account id

2023-07-05 19:48 UTC, hahnd commented on docs/_static/install_13b_wrf_pipeline.png
blur username/account id

2023-07-05 19:48 UTC, hahnd commented on docs/_static/install_13c_building.png
blur username/account id

2023-07-05 19:48 UTC, hahnd commented on docs/_static/install_13d_steps.png
blur username/account id

2023-07-05 19:48 UTC, hahnd commented on docs/_static/install_9a_select_stack.png
blur username/account id

2023-07-05 19:48 UTC, hahnd commented on docs/_static/install_9b_select_events.png
blur username/account id

2023-07-05 19:48 UTC, hahnd commented on docs/_static/uninstall_4a_search_ec2.png
blur username/account id

2023-07-05 19:48 UTC, hahnd commented on docs/_static/uninstall_4ca_amis.png
blur account id

2023-07-05 19:48 UTC, hahnd commented on docs/_static/uninstall_4db_delete_snapshot.png
blur username/account id

2023-07-05 19:48 UTC, hahnd commented on docs/_static/uninstall_4ea_delete_ssh.png
blur username/account id

2023-07-05 19:48 UTC, hahnd commented on docs/_static/uninstall_6a_cf.png
blur username/account id

2023-07-05 20:55 UTC, hahnd requested changes

2023-07-05 20:55 UTC, hahnd commented on docs/_static/uninstall_4ea_delete_ssh.png
Maybe hide all of our usernames and SSH key fingerprints here too.

2023-07-05 20:55 UTC, hahnd commented on docs/_static/uninstall_4ca_amis.png
blur account id here.  It is in the ARN in the search auto-complete.

2023-07-05 20:55 UTC, hahnd commented on docs/_static/install_11_login.png
blur-out your email address and password length.

2023-07-05 21:02 UTC, hahnd approved these changes

2023-07-06 17:28 UTC, fossell approved these changes
The screen shots are a great addition, the text overlay directions are clear and helpful. Looks good!

2023-07-06 18:32 UTC, merged