Add post processing with UPP to runtime
NCAR/wrfcloud pull request #81
Opened 2022-10-04 16:04 UTC by fossell

## Expected Differences ##

- [ ] Do these changes modify the system output in any way? **[No]**</br>
These changes add UPP grib2 output files, they do not change existing output. 

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>
The test case was performed on the AWS cluster and with just a couple forecast hours, e.g. editing test.yml enddate to only process two forecast hours.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
- [ ] Review the source issue metadata (labels, project, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Project**
Select: **Milestone** as the version that will include these changes
Select: **Development** to link to the original development issue.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2022-10-05 14:38 UTC, fossell commented on python/src/wrfcloud/runtime/postproc.py
> +            self.submit_job('unipost.exe',self.runinfo.wrfcores,'wrf')
Should we use wrfcores? Or implement component specific settings where it makes sense, e.g. uppcores?

2022-10-05 23:36 UTC, hahnd commented on python/src/wrfcloud/runtime/postproc.py
> +            fhr = fhr + 1
I think that _fhr_ abbreviation is forecast hour?  Should this be fhr += self.runinfo.output_freq_sec / 3600; or is it really just an output step and not a forecast hour?

2022-10-05 23:36 UTC, hahnd reviewed
I made a few suggested changes in [this branch](https://github.com/NCAR/wrfcloud/tree/feature-51/add_upp_script_dh_codereview).

2022-10-06 16:19 UTC, mkavulich requested changes
A few comments and requested changes. Let me know if you have questions!

2022-10-06 16:19 UTC, mkavulich commented on python/src/wrfcloud/runtime/postproc.py
> +            self.submit_job('unipost.exe',self.runinfo.wrfcores,'wrf')
I think it makes sense to have a separate setting for UPP (and maybe real.exe and WPS too) given the potential for over-decomposition problems. But I think it's fine to leave it this way for now given we're only using this one domain on this one machine.

2022-10-06 16:19 UTC, mkavulich commented on python/src/wrfcloud/runtime/postproc.py
> +        enddate   = datetime.strptime(enddate, '%Y-%m-%d_%H:%M:%S')
"startdate" and "enddate" don't need to be local variables here; just reference `self.runinfo.enddate` and `self.runinfo.startdate` directly where needed.

2022-10-06 16:26 UTC, mkavulich commented on python/src/wrfcloud/runtime/postproc.py
> +        enddate   = datetime.strptime(enddate, '%Y-%m-%d_%H:%M:%S')
My original comment was incorrect, but these lines can be consolidated (similar to logic in `__init__.py`)

```suggestion
        startdate = datetime.strptime(self.runinfo.startdate, '%Y-%m-%d_%H:%M:%S')
        enddate   = datetime.strptime(self.runinfo.enddate, '%Y-%m-%d_%H:%M:%S')
```

2022-10-06 18:08 UTC, fossell commented on python/src/wrfcloud/runtime/postproc.py
> +            fhr = fhr + 1
@hahnd @mkavulich - Good catch! That was leftover from testing and forgot to update to be general.

2022-10-06 18:09 UTC, fossell commented on python/src/wrfcloud/runtime/postproc.py
> +        enddate   = datetime.strptime(enddate, '%Y-%m-%d_%H:%M:%S')
This didn't work originally but I can't remember why, it may have been because i was originally only doing an import datetime. I will try to this again and test

2022-10-06 18:10 UTC, fossell commented on python/src/wrfcloud/runtime/postproc.py
> +            self.submit_job('unipost.exe',self.runinfo.wrfcores,'wrf')
Sounds good. I'll make this a separate issue for enhancement later.

2022-10-06 21:41 UTC, fossell commented
@hahnd @mkavulich - I committed your suggested changes and tested them, all works as expected. Please review again and approve if ready.

2022-10-07 17:28 UTC, hahnd approved these changes

2022-10-07 18:04 UTC, merged