Feature 57/run wrf api
NCAR/wrfcloud pull request #88
Opened 2022-10-26 19:30 UTC by fossell

## Expected Differences ##

- [ ] Do these changes modify the system output in any way? **[Yes or No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
- [ ] Review the source issue metadata (labels, project, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Project**
Select: **Milestone** as the version that will include these changes
Select: **Development** to link to the original development issue.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2022-10-26 19:32 UTC, fossell commented on python/src/wrfcloud/api/actions/wrf.py
> +                     f'wrfcloud-run > log.wrfcloud-run 2>&1 & \n'
This currently doesn't work, an error results saying the command can't be found. But you can connect to the cluster and manually run it. Need to unset MPI env var above to manually run otherwise metgrid fails. 
Error for log.wrfcloud-run:
`/tmp/tmp.6Cbs5fichr: line 11: wrfcloud-run: command not found
`

2022-10-26 19:34 UTC, fossell commented on python/src/wrfcloud/api/actions/wrf.py
> +            config_file['run']['local_data'] = f'/data/{self.ref_id}/gfs.t*'
This should probably be deleted or set to empty by default eventually. We will want the scripts to automatically pull data for a given forecast date. I tested this manually and it works as expected. (Need to ensure start date hour is only 00, 06, 12, 18).  For testing purposes, having local_data set here is ok for now.

2022-10-26 19:38 UTC, fossell commented on python/src/wrfcloud/api/actions/wrf.py
> +            config_file['run']['workdir'] = f'/data/{config_name}_run'
How do we want the output organized? Does it matter? Tried /data/{self.ref_id}/{config_name}_run/ but that failed to have write permissions in /data/self.ref_id when manually testing. So opted for /data/{config_name}_run/.

2022-10-26 19:39 UTC, fossell commented on python/src/wrfcloud/api/actions/wrf.py
> +            # create the run configuration file
This is very messy, but it works. Open to improvements and best practice modifications.

2022-10-26 19:57 UTC, fossell commented on python/src/wrfcloud/api/actions/wrf.py
> +                     f'wrfcloud-run > log.wrfcloud-run 2>&1 & \n'
Error on cluster: wrfcloud-run command not found.
Also, metgrid will fail even if running manually bc head node is c5 w/o efa support, so need to manually unset MPI variable in line above for success.

2022-10-31 16:58 UTC, hahnd commented on python/src/wrfcloud/aws/pcluster.py
> +        # did not find a match
Maybe log a warning if the subnet ID is not found.

2022-10-31 17:53 UTC, hahnd commented on python/src/wrfcloud/api/actions/wrf.py
> +                     f'wrfcloud-run > log.wrfcloud-run 2>&1 & \n'
Try changing the [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) line to `#! /usr/bin/su ec2-user` to get the whole script to run as ec2-user.  If it still fails to find the `wrfcloud-run` command, then try adding `source /etc/bashrc` as the first line after the shebang.  That should get the path setup properly.

2022-10-31 17:57 UTC, hahnd commented on python/src/wrfcloud/api/actions/wrf.py
> +                     f'wrfcloud-run > log.wrfcloud-run 2>&1 & \n'
For the EFA, maybe we can just change the head node type from c5.xlarge to c5n.xlarge.  This will have EFA support and it is a $0.04/hr difference in cost.

2022-10-31 17:58 UTC, hahnd commented on python/src/wrfcloud/api/actions/wrf.py
> +            wrfcloud_cluster.create_cluster(ca, False)
Before returning, we should add a new WrfJob to the database.  This is how we track history and communicate status to the UI.  I will make a commit on this branch with the code to do this.

2022-10-31 18:07 UTC, hahnd requested changes
See inline comments and latest commit on this branch.

2022-11-03 17:07 UTC, fossell commented on python/src/wrfcloud/api/actions/wrf.py
> +                     f'wrfcloud-run > log.wrfcloud-run 2>&1 & \n'
Unfortunately changing to the head node instance type to c5n.xlarge did not work, since it appears that type also doesn't have EFA support. I found [this documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa.html) listing the instance types with EFA support, any suggestions on what might work? Or we can just keep unsetting the environment variable for now.

2022-11-22 00:16 UTC, merged